services:
  # PostgreSQL
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=asyncflow_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # RabbitMQ
  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=secret'
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data: